name: Scratch Studio Members
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  
jobs:
  Scratch_Studio_Members:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 curators.py
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git commit -m 'Github Actions Update File' -a
      - run: git push
